[package]
name = "File-Encryption"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5"
zeroize = "1.6"
rpassword = "7.3"
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"
